### ISSUE TITLE
WalletConnectProvider not working / LaravelWeb3Scripts.php file

### ISSUE THREAD

**Issue by A-M-H-F** [sawirricardo/laravel-web3#7]
constructor() {
        this._provider = null;
        this.reloadAfterFetching = true;
        this.alertUserIfMetamaskIsNotInstalled = true;
        this.contracts = @json(config('web3.contracts'));
        this.web3ModalOptions = {
            cacheProvider: true,
            disableInjectedProvider: false,
            providerOptions: {
                walletconnect: {
                    package: WalletConnectProvider,
                    options: {
                    infuraId: "******* // hidden for post",
                    qrcodeModalOptions: {
                        desktopLinks: [
                          'ledger',
                          'tokenary',
                          'wallet',
                          'wallet 3',
                          'secuX',
                          'ambire',
                          'wallet3',
                          'apolloX',
                          'zerion',
                          'sequence',
                          'punkWallet',
                          'kryptoGO',
                          'nft',
                          'riceWallet',
                          'vision',
                          'keyring'
                        ],
                        mobileLinks: [
                          "rainbow",
                          "metamask",
                          "trust",
                        ],
                    },
                    },
                },
            },
        };
    }

Error: console log / Developer tools

Uncaught (in promise) TypeError: e is not a constructor
    at walletconnect.ts:31:22
    at tslib.es6.js:100:1
    at Object.next (tslib.es6.js:81:45)
    at tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at Module.A (tslib.es6.js:70:1)
    at walletconnect.ts:15:44
    at new Promise (<anonymous>)
    at t.default (walletconnect.ts:15:10)
    at e.<anonymous> (providers.ts:201:30)

**Comment by A-M-H-F** [comment]
I have fixed the problem, by adding

const WalletConnectProvider = window.WalletConnectProvider.default;

inside constructor()
